apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secondary-scheduler-operator
  namespace: openshift-secondary-scheduler-operator
spec:
  selector:
    matchLabels:
      name: secondary-scheduler-operator
  endpoints:
    - port: https
      scheme: https
      interval: 30s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: secondary-scheduler-operator-metrics.openshift-secondary-scheduler-operator.svc
