apiVersion: v1
kind: Service
metadata:
  name: secondary-scheduler-operator-metrics
  namespace: openshift-secondary-scheduler-operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: secondary-scheduler-operator-serving-cert
  labels:
    name: secondary-scheduler-operator
spec:
  selector:
    name: secondary-scheduler-operator
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
