kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secondary-scheduler-system-volume-scheduler-role-binding
subjects:
- kind: ServiceAccount
  name: secondary-scheduler-operator
  namespace: openshift-secondary-scheduler-operator
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
