apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondary-scheduler-operator
  namespace: openshift-secondary-scheduler-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secondary-scheduler-operator
  template:
    metadata:
      labels:
        name: secondary-scheduler-operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: secondary-scheduler-operator
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          image: quay.io/openshift/secondary-scheduler-operator:4.17
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - secondary-scheduler-operator
          args:
          - "operator"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "secondary-scheduler-operator"
          volumeMounts:
          - name: tmp
            mountPath: "/tmp"
      serviceAccountName: secondary-scheduler-operator
      serviceAccount: secondary-scheduler-operator
      volumes:
      - name: tmp
        emptyDir: {}
